import path from "path";
import fs from "fs";

import type { AllConfigs } from "./config.generated";

type RawStore = Record<string, Record<string, unknown>>;

function createConfigProxy(): AllConfigs {
  const cache: RawStore = {};

  const generatedDir = path.resolve(__dirname, "..", "generated");

  function loadNamespace(name: string): Record<string, unknown> {
    if (cache[name]) return cache[name];

    const filePath = path.join(generatedDir, `${name}.js`);
    if (!fs.existsSync(filePath)) {
      throw new Error(
          `[ease-config] No generated config for namespace "${name}".\n` +
          `Run: npx ease-config generate`
      );
    }

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    cache[name] = require(filePath) as Record<string, unknown>;
    return cache[name];
  }

  return new Proxy({} as AllConfigs, {
    get(_target, namespace: string | symbol) {
      if (typeof namespace !== "string") return undefined;
      const ns = loadNamespace(namespace);

      return new Proxy({} as AllConfigs[keyof AllConfigs], {
        get(_t, key: string | symbol) {
          if (typeof key !== "string") return undefined;
          if (!(key in ns)) {
            throw new Error(`[ease-config] config.${namespace}.${key} does not exist.`);
          }
          return ns[key];
        },
        has(_t, key) {
          return typeof key === "string" && key in ns;
        },
        ownKeys() {
          return Object.keys(ns);
        },
        getOwnPropertyDescriptor(_t, key) {
          if (typeof key === "string" && key in ns) {
            return { configurable: true, enumerable: true, value: ns[key] };
          }
          return undefined;
        },
      });
    },
  });
}

/**
 * Synchronous accessor for configuration — the type comes directly from AllConfigs,
 * generated by `npx ease-config generate` based on the config/*.ts files.
 *
 * @example
 * import { config } from "@ease/config";
 *
 * config.app.port   // type: 3000
 * config.db.host    // type: "127.0.0.1"
 * config.app.wtf    // ✗ TS error: Property 'wtf' does not exist on AllConfigs["app"]
 */
export const config: AllConfigs = createConfigProxy();
