import path from "path";
import fs from "fs";
import os from "os";

interface GenerateOptions {
  projectRoot: string;
  configDir: string;
}

interface CorePaths {
  coreDir: string;
  distDir: string;
  generatedDir: string;
}

function resolveCorePaths(projectRoot: string): CorePaths {
  const candidates = [
    path.join(projectRoot, "node_modules", "@ease", "config"),
  ];
  for (const coreDir of candidates) {
    if (fs.existsSync(coreDir)) {
      return {
        coreDir,
        distDir: path.join(coreDir, "dist"),
        generatedDir: path.join(coreDir, "generated"),
      };
    }
  }
  throw new Error(
      `[ease-config] Cannot find core package in node_modules.\n` +
      `Make sure you ran: npm install @ease/config`
  );
}

function loadConfigValues(filePath: string): Record<string, unknown> {
  const tmpFile = path.join(
      os.tmpdir(),
      `ease-${Date.now()}-${path.basename(filePath, ".ts")}.cjs`
  );

  try {
    const { buildSync } = require("esbuild") as typeof import("esbuild");
    buildSync({
      entryPoints: [filePath],
      bundle: true,
      platform: "node",
      format: "cjs",
      outfile: tmpFile,
      external: ["@nestjs/*", "reflect-metadata", "rxjs", "class-transformer", "class-validator"],
      logLevel: "silent",
    });
  } catch (err) {
    throw new Error(
        `[ease-config] Failed to bundle config file: ${filePath}\n` +
        `Make sure esbuild is installed: npm install --save-dev esbuild\n${err}`
    );
  }

  try {
    delete require.cache[tmpFile];
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const mod = require(tmpFile) as Record<string, unknown>;
    const raw = mod?.default ?? mod;
    if (raw && typeof raw === "object" && (raw as Record<string, unknown>).__brand === "ConfigDefinition") {
      return (raw as { value: Record<string, unknown> }).value;
    }
    return raw as Record<string, unknown>;
  } finally {
    try { fs.unlinkSync(tmpFile); } catch { /* ignore */ }
  }
}

function toTsType(value: unknown, indent = ""): string {
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  switch (typeof value) {
    case "string":  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
    case "number":  return String(value);
    case "boolean": return String(value);
    case "object":
      if (Array.isArray(value)) {
        if (value.length === 0) return "never[]";
        const types = [...new Set(value.map((v) => toTsType(v, indent)))];
        return `Array<${types.join(" | ")}>`;
      } else {
        const obj = value as Record<string, unknown>;
        const inner = Object.entries(obj)
            .map(([k, v]) => `${indent}    ${k}: ${toTsType(v, indent + "  ")}`)
            .join(";\n");
        return `{\n${inner}\n${indent}  }`;
      }
    default: return "unknown";
  }
}

function generateNamespaceJs(values: Record<string, unknown>): string {
  return [
    `// AUTO-GENERATED by @ease/config-cli — do not edit`,
    `"use strict";`,
    `module.exports = ${JSON.stringify(values, null, 2)};`,
    ``,
  ].join("\n");
}

/**
 * Generuje dist/index.d.ts nadpisując typ `config` na AllConfigs z literałami.
 *
 * Strategia: zamiast próbować importować typy z generated/ (problem z rootDirs
 * po kompilacji), generator bezpośrednio nadpisuje dist/index.d.ts — plik który
 * TypeScript czyta gdy użytkownik robi `import { config } from "@nest-ease/config"`.
 *
 *   export declare const config: {
 *     readonly main: {
 *       readonly port: 3000;
 *       readonly host: "localhost";
 *     };
 *   };
 */
function generateDistIndexDts(
    originalDts: string,
    namespaces: Array<{ name: string; values: Record<string, unknown> }>
): string {
  const configType = namespaces
      .map(({ name, values }) => {
        const props = Object.entries(values)
            .map(([key, val]) => `    readonly ${key}: ${toTsType(val)};`)
            .join("\n");
        return `  readonly ${name}: {\n${props}\n  };`;
      })
      .join("\n");

  const typed = originalDts.replace(
      /export declare const config:.*?;/s,
      `export declare const config: {\n${configType}\n};`
  );

  return [
    `// AUTO-GENERATED by @ease/config-cli — do not edit manually`,
    `// Run: npx ease-config generate`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
    typed !== originalDts ? typed : `${originalDts}\n\nexport declare const config: {\n${configType}\n};`,
  ].join("\n");
}

export async function generate(options: GenerateOptions): Promise<void> {
  const { projectRoot, configDir } = options;

  if (!fs.existsSync(configDir)) {
    throw new Error(`[ease-config] Config directory not found: ${configDir}`);
  }

  const { distDir, generatedDir } = resolveCorePaths(projectRoot);
  fs.mkdirSync(generatedDir, { recursive: true });

  const tsFiles = fs
      .readdirSync(configDir)
      .filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts"));

  if (tsFiles.length === 0) {
    console.warn(`[ease-config] No .ts files found in ${configDir}`);
    return;
  }

  const collected: Array<{ name: string; values: Record<string, unknown> }> = [];

  for (const file of tsFiles) {
    const namespace = path.basename(file, ".ts");
    const filePath = path.join(configDir, file);
    console.log(`[ease-config] Processing ${file} → ${namespace}.*`);

    const values = loadConfigValues(filePath);
    collected.push({ name: namespace, values });

    // Runtime JS z wartościami — ładowany przez Proxy w config.ts
    fs.writeFileSync(
        path.join(generatedDir, `${namespace}.js`),
        generateNamespaceJs(values),
        "utf8"
    );
  }

  const distIndexDts = path.join(distDir, "index.d.ts");
  if (!fs.existsSync(distIndexDts)) {
    throw new Error(
        `[ease-config] dist/index.d.ts not found. Build core first:\n  npm run build -w packages/config`
    );
  }

  const original = fs.readFileSync(distIndexDts, "utf8");
  fs.writeFileSync(distIndexDts, generateDistIndexDts(original, collected), "utf8");

  console.log(`\n[ease-config] ✓ ${collected.length} namespace(s): ${collected.map(c => c.name).join(", ")}`);
  console.log(`[ease-config] ✓ Patched dist/index.d.ts with typed config`);
  console.log(`[ease-config] ✓ Output: ${generatedDir}\n`);
}
