import path from "path";
import fs from "fs";
import os from "os";

export interface GenerateOptions {
  projectRoot: string;
  configDir: string;
}

function resolveDistDir(projectRoot: string): string {
  const distDir = path.join(projectRoot, "node_modules", "@ease", "config", "dist");
  if (fs.existsSync(distDir)) return distDir;
  throw new Error(`[ease-config] Cannot find core package dist/ in node_modules.\nMake sure you ran: npm install`);
}

const SHIM = `
"use strict";
(function() {
  const Module = require("module");
  const __shimExports = {
    defineConfig: function(cfg) { return { __brand: "ConfigDefinition", value: cfg }; },
    env: function(key, fallback) { return { __brand: "EnvValue", key: key, fallback: fallback }; },
  };
  const __origLoad = Module._load.bind(Module);
  Module._load = function(request, parent, isMain) {
    if (request === "@nest-ease/config" || request === "@mylib/core") {
      return __shimExports;
    }
    return __origLoad(request, parent, isMain);
  };
})();
`;

interface EnvValueRaw {
  __brand: "EnvValue";
  key: string;
  fallback: unknown;
}

function isEnvValue(v: unknown): v is EnvValueRaw {
  return (typeof v === "object" && v !== null && (v as Record<string, unknown>).__brand === "EnvValue");
}

function loadRawConfig(filePath: string): Record<string, unknown> {
  const tmpFile = path.join(os.tmpdir(), `ease-config-${Date.now()}-${path.basename(filePath, ".ts")}.cjs`);

  try {
    const { buildSync } = require("esbuild") as typeof import("esbuild");
    buildSync({
      entryPoints: [filePath],
      bundle: true,
      platform: "node",
      format: "cjs",
      outfile: tmpFile,
      external: [
        "@nest-ease/config",
        "@nest-ease/*",
        "@mylib/core",
        "@nestjs/*",
        "reflect-metadata",
        "rxjs",
        "class-transformer",
        "class-validator",
      ],
      logLevel: "silent",
      banner: { js: SHIM },
    });
  } catch (err) {
    throw new Error(`[ease-config] Failed to bundle ${path.basename(filePath)}.\nMake sure esbuild is installed: npm install --save-dev esbuild\n${err}`);
  }

  try {
    delete require.cache[tmpFile];
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const mod = require(tmpFile) as Record<string, unknown>;
    const raw = mod?.default ?? mod;

    if (raw && typeof raw === "object" && (raw as Record<string, unknown>).__brand === "ConfigDefinition") {
      return (raw as { value: Record<string, unknown> }).value;
    }
    return raw as Record<string, unknown>;
  } finally {
    try { fs.unlinkSync(tmpFile); } catch { /* ignore */ }
  }
}

/**
 * EnvValue:
 *   env("PORT", 3000)        → number
 *   env("HOST", "localhost") → string
 *   env("DEBUG", false)      → boolean
 *   env("SECRET")            → string
 *
 * Const values:
 *   3000        → 3000
 *   "localhost" → "localhost"
 *   true        → true
 */
function toTsType(value: unknown, indent = ""): string {
  if (isEnvValue(value)) {
    if (value.fallback === undefined) return "string";
    switch (typeof value.fallback) {
      case "number":  return "number";
      case "boolean": return "boolean";
      default:        return "string";
    }
  }

  if (value === null) return "null";
  if (value === undefined) return "undefined";

  switch (typeof value) {
    case "string":  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
    case "number":  return String(value);
    case "boolean": return String(value);
    case "object":
      if (Array.isArray(value)) {
        if (value.length === 0) return "never[]";
        const types = [...new Set(value.map((v) => toTsType(v, indent)))];
        return `Array<${types.join(" | ")}>`;
      } else {
        const obj = value as Record<string, unknown>;
        const inner = Object.entries(obj)
            .map(([k, v]) => `${indent}    readonly ${k}: ${toTsType(v, indent + "  ")}`)
            .join(";\n");
        return `{\n${inner}\n${indent}  }`;
      }
    default: return "unknown";
  }
}

function generateDistIndexDts(
    originalDts: string,
    namespaces: Array<{ name: string; rawValues: Record<string, unknown> }>
): string {
  const configType = namespaces
      .map(({ name, rawValues }) => {
        const props = Object.entries(rawValues)
            .map(([key, val]) => `    readonly ${key}: ${toTsType(val)};`)
            .join("\n");
        return `  readonly ${name}: {\n${props}\n  };`;
      })
      .join("\n");

  const replacement = `export declare const config: {\n${configType}\n};`;

  const patched = originalDts.replace(/export declare const config:[\s\S]*?(?=\nexport|\n\/\/|$)/, replacement + "\n");

  const header = [
    `// AUTO-GENERATED by @ease/config-cli — do not edit manually`,
    `// Run: npx ease-config generate`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
  ].join("\n");

  return header + (patched !== originalDts ? patched : `${originalDts}\n${replacement}\n`);
}

export async function generate(options: GenerateOptions): Promise<void> {
  const { projectRoot, configDir } = options;

  if (!fs.existsSync(configDir)) {
    throw new Error(`[ease-config] Config directory not found: ${configDir}`);
  }

  const distDir = resolveDistDir(projectRoot);

  const tsFiles = fs
      .readdirSync(configDir)
      .filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts"));

  if (tsFiles.length === 0) {
    console.warn(`[ease-config] No .ts files found in ${configDir}`);
    return;
  }

  const collected: Array<{ name: string; rawValues: Record<string, unknown> }> = [];

  for (const file of tsFiles) {
    const namespace = path.basename(file, ".ts");
    const filePath = path.join(configDir, file);
    console.log(`[ease-config] Processing ${file}…`);

    const rawValues = loadRawConfig(filePath);
    collected.push({ name: namespace, rawValues });
  }

  const distIndexDts = path.join(distDir, "index.d.ts");
  if (!fs.existsSync(distIndexDts)) {
    throw new Error(`[ease-config] dist/index.d.ts not found.\n` + `Build config core first: npm run build -w packages/config`);
  }

  const original = fs.readFileSync(distIndexDts, "utf8");
  fs.writeFileSync(distIndexDts, generateDistIndexDts(original, collected), "utf8");

  const summary = collected
      .map(({ name, rawValues }) => {
        const keys = Object.keys(rawValues).join(", ");
        return `  ${name}: { ${keys} }`;
      })
      .join("\n");

  console.log(`\n[ease-config] ✓ Types generated for ${collected.length} namespace(s):`);
  console.log(summary);
  console.log(`\n[ease-config] ✓ Patched: ${distIndexDts}`);
  console.log(`[ease-config] ✓ Values loaded at runtime from: ${configDir}\n`);
}
